
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author sebya
 */
public class Interogari extends javax.swing.JFrame {

    /**
     * Creates new form Interogari
     */
    public Interogari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboBox1 = new javax.swing.JComboBox();
        Query1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Query2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ComboBox2 = new javax.swing.JComboBox();
        Query3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ComboBox3 = new javax.swing.JComboBox();
        Query4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ComboBox4 = new javax.swing.JComboBox();
        Query5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ComboBox5 = new javax.swing.JComboBox();
        Query6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ComboBox6 = new javax.swing.JComboBox();
        Query7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Query8 = new javax.swing.JButton();
        TextField3 = new javax.swing.JTextField();
        Query9 = new javax.swing.JButton();
        Query10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Interogari");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("1. Afisati animalele ce fac parte din categoria");

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bovine", "Caprine", "Ecvide", "Phasianide" }));

        Query1.setBackground(new java.awt.Color(255, 255, 255));
        Query1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query1.setForeground(new java.awt.Color(51, 102, 255));
        Query1.setText("Query 1");
        Query1.setBorder(null);
        Query1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("2. Afisati numele si prenumele si nr de ore lucrate pentru angajatii ce lucreaza peste");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ore pe saptamana");

        Query2.setBackground(new java.awt.Color(255, 255, 255));
        Query2.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query2.setForeground(new java.awt.Color(51, 102, 255));
        Query2.setText("Query 2");
        Query2.setBorder(null);
        Query2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("3. Afisati numele si prenumele angajatilor ce lucreaza la incinta");

        ComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cotet", "Grajd", "Hambar", "Curte" }));

        Query3.setBackground(new java.awt.Color(255, 255, 255));
        Query3.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query3.setForeground(new java.awt.Color(51, 102, 255));
        Query3.setText("Query 3");
        Query3.setBorder(null);
        Query3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("4. Afisati animalele care mananca de la furnizorul ");

        ComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IarbaSRL", "Moara", "Sera" }));

        Query4.setBackground(new java.awt.Color(255, 255, 255));
        Query4.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query4.setForeground(new java.awt.Color(51, 102, 255));
        Query4.setText("Query 4");
        Query4.setBorder(null);
        Query4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("5. Afisati angajatii ce trebuie sa administreze medicament pentru");

        ComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Capra", "Cal", "Gaina", "Vaca" }));

        Query5.setBackground(new java.awt.Color(255, 255, 255));
        Query5.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query5.setForeground(new java.awt.Color(51, 102, 255));
        Query5.setText("Query 5");
        Query5.setBorder(null);
        Query5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("6. Afisati ora la care sunt hranite animalele ce sunt");

        ComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bovine", "Caprine", "Ecvide", "Phasianide" }));

        Query6.setBackground(new java.awt.Color(255, 255, 255));
        Query6.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query6.setForeground(new java.awt.Color(51, 102, 255));
        Query6.setText("Query 6");
        Query6.setBorder(null);
        Query6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query6ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("7. Afisati angajatii care lucreaza cel putin");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ore la incinta la care se furnizeaza mancare de la ");

        ComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IarbaSRL", "Moara", "Sera" }));

        Query7.setBackground(new java.awt.Color(255, 255, 255));
        Query7.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query7.setForeground(new java.awt.Color(51, 102, 255));
        Query7.setText("Query 7");
        Query7.setBorder(null);
        Query7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query7ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("10. Afisati angajatii ce lucreaza la o incinta cu capacitate peste medie");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("9. Afisati angajatii care trebuie sa hraneasca animalele inainte de ora");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("8. Sa se determine incinta de lucru unde se ofera un salariu peste media tuturor salariilor");

        Query8.setBackground(new java.awt.Color(255, 255, 255));
        Query8.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query8.setForeground(new java.awt.Color(51, 102, 255));
        Query8.setText("Query 8");
        Query8.setBorder(null);
        Query8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query8ActionPerformed(evt);
            }
        });

        Query9.setBackground(new java.awt.Color(255, 255, 255));
        Query9.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query9.setForeground(new java.awt.Color(51, 102, 255));
        Query9.setText("Query 9");
        Query9.setBorder(null);
        Query9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query9ActionPerformed(evt);
            }
        });

        Query10.setBackground(new java.awt.Color(255, 255, 255));
        Query10.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Query10.setForeground(new java.awt.Color(51, 102, 255));
        Query10.setText("Query 10");
        Query10.setBorder(null);
        Query10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Query10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query10ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\sebya\\Desktop\\BD\\index.png")); // NOI18N
        jLabel14.setText("jLabel14");

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\sebya\\Desktop\\BD\\Annotation 2020-01-07 230643.jpg")); // NOI18N
        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel13)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel11)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(132, 132, 132))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(347, 347, 347)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(149, 149, 149)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Query3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Query6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Query10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Query8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Query9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Query7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Query5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Query4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Query2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Query1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(156, 156, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Query1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Query2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Query3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Query4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Query5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Query6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Query7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Query8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Query9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Query10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Query1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query1ActionPerformed
        // Querry 1
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query1 = "SELECT A.Denumire, C.Tip\n" +
                            "FROM Animale A INNER JOIN Categorie C\n" +
                            "ON A.IDAnimale = C. IDAnimale\n" +
                            "AND C.Tip = ?";            
            PreparedStatement ps = con.prepareStatement(query1);
            ps.setString(1,ComboBox1.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_Query1ActionPerformed

    private void Query2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query2ActionPerformed
        // Querry 2
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query2 = "SELECT AA.Nume, AA.Prenume, L.NROreSaptamana\n" +
                            "FROM Angajat AA INNER JOIN Lucreaza L\n" +
                            "ON AA.IDAngajat = L.IDAngajat\n" +
                            "WHERE L.NROreSaptamana > ?";
            PreparedStatement ps = con.prepareStatement(query2);
            ps.setString(1,TextField1.getText());
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Query2ActionPerformed

    private void Query3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query3ActionPerformed
        // Querry 3
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query3 = "SELECT AA.Nume, AA.Prenume\n" +
                            "FROM Angajat AA INNER JOIN Lucreaza L\n" +
                            "ON AA.IDAngajat = L.IDAngajat INNER JOIN Incinte I ON L.IDIncinta = I.IDIncinta\n" +
                            "WHERE I.Denumire = ?";
            PreparedStatement ps = con.prepareStatement(query3);
            ps.setString(1,ComboBox2.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Query3ActionPerformed

    private void Query4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query4ActionPerformed
        // Querry 4
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query4 = "SELECT A.Denumire\n" +
                            "FROM Animale A INNER JOIN Hranire H ON A.IDAnimale = H.IDAnimale\n" +
                            "INNER JOIN Hrana HH ON H.IDHrana = HH.IDHrana\n" +
                            "WHERE Furnizor = ?";
            PreparedStatement ps = con.prepareStatement(query4);
            ps.setString(1,ComboBox3.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Query4ActionPerformed

    private void Query5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query5ActionPerformed
        // Querry 5
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query5 = "SELECT A.Nume, A.Prenume\n" +
                            "FROM Angajat A INNER JOIN Lucreaza L ON A.IDAngajat = L.IDAngajat\n" +
                            "INNER JOIN Incinte I ON L.IDIncinta = I.IDIncinta INNER JOIN Animale AA\n" +
                            "ON AA.IDIncinta = I.IDIncinta\n" +
                            "WHERE AA.Denumire = ?";
            PreparedStatement ps = con.prepareStatement(query5);
            ps.setString(1,ComboBox4.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Query5ActionPerformed

    private void Query6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query6ActionPerformed
        // Querry 6
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query6 = "SELECT H.Ora\n" +
                            "FROM Hranire H INNER JOIN Animale A ON H.IDAnimale = A.IDAnimale\n" +
                            "INNER JOIN Categorie C ON C.IDAnimale = A.IDAnimale\n" +
                            "WHERE C.Tip = ?";
            PreparedStatement ps = con.prepareStatement(query6);
            ps.setString(1,ComboBox5.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Query6ActionPerformed

    private void Query7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query7ActionPerformed
        // Querry 7
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query7 = "SELECT A.Nume, A.Prenume\n" +
                            "FROM Angajat A INNER JOIN Lucreaza L ON A.IDAngajat = L.IDAngajat\n" +
                            "WHERE L.NROreSaptamana > ? AND L.IDIncinta IN\n" +
                            "(SELECT AA.IDIncinta FROM Animale AA INNER JOIN Hranire H\n" +
                            "ON AA.IDAnimale = H.IDAnimale INNER JOIN Hrana HH ON\n" +
                            "H.IDHrana = HH.IDHrana\n" +
                            "WHERE HH.Furnizor = ? )";
            PreparedStatement ps = con.prepareStatement(query7);
            ps.setString(1,TextField2.getText());
            ps.setString(2,ComboBox6.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Query7ActionPerformed

    private void Query8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query8ActionPerformed
        // Querry 8
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query8 = "SELECT I.Denumire, AVG (A.Salariu) as SalariuMediu\n" +
                            "FROM Angajat A INNER JOIN Lucreaza L ON A.IDAngajat = L.IDAngajat INNER JOIN Incinte I ON L.IDIncinta = I.IDIncinta GROUP BY I.Denumire\n" +
                            "HAVING AVG(A.Salariu) > (SELECT AVG(Salariu) FROM Angajat)";
            PreparedStatement ps = con.prepareStatement(query8);
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Query8ActionPerformed

    private void Query9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query9ActionPerformed
        // Querry 9
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query9 = "SELECT A.Nume, A.Prenume\n" +
                            "FROM Angajat A INNER JOIN Lucreaza L ON A.IDAngajat = L.IDAngajat INNER JOIN Incinte I1 ON L.IDIncinta = I1.IDIncinta\n" +
                            "WHERE L.IDIncinta IN (SELECT I.IDIncinta FROM Hranire H INNER JOIN Animale A on A.IDAnimale = H.IDAnimale INNER JOIN Incinte I ON I.IDIncinta = A.IDIncinta \n" +
                            "WHERE H.Ora < ?)";
            PreparedStatement ps = con.prepareStatement(query9);
            ps.setString(1,TextField3.getText());
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Query9ActionPerformed

    private void Query10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query10ActionPerformed
        // Querry 10
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query10 = "SELECT A.Nume, AVG(I.Capacitate)\n" +
                             "FROM Angajat A INNER JOIN Lucreaza L ON A.IDAngajat=L.IDAngajat INNER JOIN Incinte I ON L.IDIncinta = I.IDIncinta GROUP BY A.Nume\n" +
                             "HAVING AVG(I.Capacitate) > (SELECT AVG(Capacitate) FROM Incinte)";
            PreparedStatement ps = con.prepareStatement(query10);
            ResultSet rs = ps.executeQuery();
            JTable table = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null,new JScrollPane(table));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Query10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interogari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interogari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interogari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interogari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interogari().setVisible(true);
            }
        });
    }
    // Functie pentru afisarea rezultatelor intr-o fereastra Pop-up
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }

    return new DefaultTableModel(data, columnNames);

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox1;
    private javax.swing.JComboBox ComboBox2;
    private javax.swing.JComboBox ComboBox3;
    private javax.swing.JComboBox ComboBox4;
    private javax.swing.JComboBox ComboBox5;
    private javax.swing.JComboBox ComboBox6;
    private javax.swing.JButton Query1;
    private javax.swing.JButton Query10;
    private javax.swing.JButton Query2;
    private javax.swing.JButton Query3;
    private javax.swing.JButton Query4;
    private javax.swing.JButton Query5;
    private javax.swing.JButton Query6;
    private javax.swing.JButton Query7;
    private javax.swing.JButton Query8;
    private javax.swing.JButton Query9;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField2;
    private javax.swing.JTextField TextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
