
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sebya
 */
public class ModificareIncinta extends javax.swing.JFrame {

    public ModificareIncinta() {
        initComponents();
        show_incinta();
    }
    //Aducerea incintelor in interfata prin conexiune si select
    public ArrayList<Incinta> incintaList(){
        ArrayList<Incinta> incinteList = new ArrayList<>();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query_1 = "SELECT * FROM Incinte";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query_1);
            Incinta incinta;
            while(rs.next()){
                incinta = new Incinta(rs.getString("Denumire"), rs.getString("Capacitate"));

                incinteList.add(incinta);    
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return incinteList;
    }
    //Functia de afisare a incintelor in interfata
    public void show_incinta(){
        ArrayList<Incinta> list = incintaList();
        DefaultTableModel model = (DefaultTableModel)Table_incinte.getModel();
        Object[] row = new Object[2];
        for(int i = 0; i<list.size(); i++){

            row[0] = list.get(i).getDenumire();
            row[1] = list.get(i).getCapacitate();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Denumire = new javax.swing.JTextField();
        Capacitate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Save_Btn = new javax.swing.JButton();
        Reset_Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_incinte = new javax.swing.JTable();
        Update_Btn = new javax.swing.JButton();
        Delete_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Modificare tabela Incinte");

        Denumire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenumireActionPerformed(evt);
            }
        });

        Capacitate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacitateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Denumire");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Capacitate");

        Save_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Save_Btn.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Save_Btn.setForeground(new java.awt.Color(51, 102, 255));
        Save_Btn.setText("Save");
        Save_Btn.setBorder(null);
        Save_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_BtnActionPerformed(evt);
            }
        });

        Reset_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Reset_Btn.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Reset_Btn.setForeground(new java.awt.Color(51, 102, 255));
        Reset_Btn.setText("Reset");
        Reset_Btn.setBorder(null);
        Reset_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reset_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_BtnActionPerformed(evt);
            }
        });

        Table_incinte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Denumire", "Capacitate"
            }
        ));
        Table_incinte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_incinteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_incinte);

        Update_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Update_Btn.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Update_Btn.setForeground(new java.awt.Color(51, 102, 255));
        Update_Btn.setText("Update");
        Update_Btn.setBorder(null);
        Update_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_BtnActionPerformed(evt);
            }
        });

        Delete_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Delete_Btn.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Delete_Btn.setForeground(new java.awt.Color(51, 102, 255));
        Delete_Btn.setText("Delete");
        Delete_Btn.setBorder(null);
        Delete_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Denumire, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(Capacitate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Save_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(Update_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(Delete_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(Reset_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Denumire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Capacitate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DenumireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenumireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DenumireActionPerformed

    private void CapacitateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacitateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacitateActionPerformed

    private void Save_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_BtnActionPerformed
        // Functia de Insert
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            String query = "INSERT into Incinte(Denumire, Capacitate)values(?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, Denumire.getText());
            pst.setString(2, Capacitate.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)Table_incinte.getModel();
            model.setRowCount(0);
            show_incinta();
            JOptionPane.showMessageDialog(null, "Inserare Reusita");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Save_BtnActionPerformed

    private void Reset_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_BtnActionPerformed
        // Resetarea campurilor
        Denumire.setText("");
        Capacitate.setText("");
    }//GEN-LAST:event_Reset_BtnActionPerformed

    private void Table_incinteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_incinteMouseClicked
        // Selectarea incintelor prin Click
        int i = Table_incinte.getSelectedRow();
        TableModel model = Table_incinte.getModel();
        Denumire.setText(model.getValueAt(i, 0).toString());
        Capacitate.setText(model.getValueAt(i, 1).toString());
    }//GEN-LAST:event_Table_incinteMouseClicked

    private void Update_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_BtnActionPerformed
        // Functia de Update
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            int row = Table_incinte.getSelectedRow();
            String value = (Table_incinte).getModel().getValueAt(row, 0).toString();
            String query_2 = "UPDATE Incinte SET Denumire=?, Capacitate=? WHERE Denumire="+"'"+value+"'";
            PreparedStatement pst = con.prepareStatement(query_2);
            pst.setString(1, Denumire.getText());
            pst.setString(2, Capacitate.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)Table_incinte.getModel();
            model.setRowCount(0);
            show_incinta();
            JOptionPane.showMessageDialog(null, "Updated");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Update_BtnActionPerformed

    private void Delete_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_BtnActionPerformed
        // Functia de Delete
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1527;databaseName=FermaAnimale;user=sa;password=SethHexFlame10";
            Connection con = DriverManager.getConnection(url);
            int row = Table_incinte.getSelectedRow();
            String value = (Table_incinte).getModel().getValueAt(row, 0).toString();
            String query = "DELETE FROM Incinte WHERE Denumire="+"'"+value+"'";
            PreparedStatement ps = con.prepareStatement(query);
            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)Table_incinte.getModel();
            model.setRowCount(0);
            show_incinta();
            JOptionPane.showMessageDialog(null, "Deleted");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Delete_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificareIncinta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificareIncinta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificareIncinta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificareIncinta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificareIncinta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Capacitate;
    private javax.swing.JButton Delete_Btn;
    private javax.swing.JTextField Denumire;
    private javax.swing.JButton Reset_Btn;
    private javax.swing.JButton Save_Btn;
    private javax.swing.JTable Table_incinte;
    private javax.swing.JButton Update_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
